package com.example.administrator.test;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.test.entity.Color;

import com.example.administrator.test.ColorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig colorDaoConfig;

    private final ColorDao colorDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        colorDaoConfig = daoConfigMap.get(ColorDao.class).clone();
        colorDaoConfig.initIdentityScope(type);

        colorDao = new ColorDao(colorDaoConfig, this);

        registerDao(Color.class, colorDao);
    }
    
    public void clear() {
        colorDaoConfig.clearIdentityScope();
    }

    public ColorDao getColorDao() {
        return colorDao;
    }

}
